### ISSUE TITLE
Controller did not Wake

### ISSUE THREAD

**Issue by Coolinmcd** [gmenounos/kw1281test#27]
Hi, I have a 2005 Audi S4 and I need the SKC code to add a couple of new keys. I have VCDS. 

I have the Ross-Tech USB cable and updated the drivers setting it to COM2. 

when I run the command I get the "controller did not wake up" error.

I've tried it at 10900 and 9600? Same error. 

I've attached the log

any assistance
[KW1281Test.log](https://github.com/gmenounos/kw1281test/files/10013110/KW1281Test.log)
 would be appreciated.

**Comment by Coolinmcd** [comment]
I've tried it at 10400 (not 10900) and 9600? Same error.

**Comment by gmenounos** [comment]
I think kw1281test isn't going to work with your car. If you look up the 2005 S4 on the following chart:
https://www.ross-tech.net/VCDS/download/VCDSCompatibilityCharts.pdf
you'll see that it requires a HEX+CAN cable because the vehicle uses CAN diagnostics. kw1281test only supports K-Line diagnostics, so for an S4 , it would only work up until model year 2004.

**Comment by Coolinmcd** [comment]
Uh ok thanks
