### ISSUE TITLE
Controller did not wake up

### ISSUE THREAD

**Issue by jneukom09** [gmenounos/kw1281test#40]
I’m also getting this issue. I downloaded the most recent version but it timed out after 2 seconds and said the controller did not wake up. I tried both 10400 and 9600.

Sorry for the double post. Wasn’t sure if you’d see my comment on the other thread.

**Comment by gmenounos** [comment]
What kind of car? You should have a kw1281test.log file. Can you please attach it?

**Comment by majkool** [comment]
Same issue with two cars:
- Skoda Octavia II 1.6 MPI 2005
- Volskwagen Golf V Plus 2007 1.9 TDI

[KW1281Test.log](https://github.com/gmenounos/kw1281test/files/11204474/KW1281Test.log)

Not much in log I think you will need to add controllers to your program. I tried 10400 and 9600 too and VCDS is working fine via USB and even COM.

Thanks in advance for support because I need to get pin.

**Comment by gmenounos** [comment]
Both of those cars use CAN-Bus diagnostics and won't work with the types of cables that kw1281test supports. Sorry. You can see the list of which cars require CAN-Bus diagnostic cables here: https://www.ross-tech.com/vcds/canbus.php
